In [1]:
import torch

In [2]:
help(torch.Storage)

Help on class FloatStorage in module torch:

class FloatStorage(torch.storage._LegacyStorage)
 |  FloatStorage(*args, wrap_storage=None, dtype=None, device=None, _internal=False)
 |  
 |  Method resolution order:
 |      FloatStorage
 |      torch.storage._LegacyStorage
 |      torch.storage.TypedStorage
 |      builtins.object
 |  
 |  Data and other attributes defined here:
 |  
 |  dtype = torch.float32
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from torch.storage.TypedStorage:
 |  
 |  __copy__(self)
 |  
 |  __deepcopy__(self, memo)
 |  
 |  __getitem__(self, idx)
 |  
 |  __init__(self, *args, device=None, dtype=None, wrap_storage=None, _internal=False)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __iter__(self)
 |  
 |  __len__(self)
 |  
 |  __reduce__(self)
 |      Helper for pickle.
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  __setitem__(self, idx, value)
 |  
 |  __s

c:\Users\howardhuang\Documents\MyCode\DeepLearningWithPytorch-SecondEdition\.venv\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()


In [3]:
torch.Storage

torch.FloatStorage

In [4]:
a = torch.tensor([1,1])

In [5]:
a

tensor([1, 1])

In [16]:
b=a[0]
b

tensor(1)

In [15]:
b.storage()

 1
 1
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 2]

In [17]:
a.storage()

 1
 1
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 2]

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)
print(points.stride())
points_t = points.t()
points_t

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
(2, 1)


tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [27]:
points_t.stride()

(1, 2)

In [22]:
points.is_contiguous()
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [19]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [25]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [20]:
points_t.is_contiguous()

False

In [24]:
points_t_cont = points_t.contiguous()
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [26]:
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [28]:
points_t_cont.stride()

(3, 1)