In [21]:
import os
# Get the current working directory (where the notebook is located)
current_dir = os.getcwd()
parent_dir = os.path.dirname(current_dir)
# Change the working directory to the parent directory
os.chdir(parent_dir)

In [23]:
!wc -l data/part2/luna/candidates.csv

551066 data/part2/luna/candidates.csv


In [ ]:
!head data/part2/luna/candidates.csv

seriesuid,coordX,coordY,coordZ,class
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,-56.08,-67.85,-311.92,0
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,53.21,-244.41,-245.17,0
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,103.66,-121.8,-286.62,0
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,-33.66,-72.75,-308.41,0
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,-32.25,-85.36,-362.51,0
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,-26.65,-203.07,-165.07,0
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,-74.99,-114.79,-311.92,0
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,-16.14,-248.61,-239.55,0
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,135.89,-141.41,-252.2,0


In [24]:
!grep ',1$' data/part2/luna/candidates.csv | wc -l

1351


In [25]:
!wc -l data/part2/luna/annotations.csv

1187 data/part2/luna/annotations.csv


In [26]:
!head data/part2/luna/annotations.csv

seriesuid,coordX,coordY,coordZ,diameter_mm
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,-128.6994211,-175.3192718,-298.3875064,5.651470635
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,103.7836509,-211.9251487,-227.12125,4.224708481
1.3.6.1.4.1.14519.5.2.1.6279.6001.100398138793540579077826395208,69.63901724,-140.9445859,876.3744957,5.786347814
1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405,-24.0138242,192.1024053,-391.0812764,8.143261683
1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405,2.441546798,172.4648812,-405.4937318,18.54514997
1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405,90.93171321,149.0272657,-426.5447146,18.20857028
1.3.6.1.4.1.14519.5.2.1.6279.6001.100621383016233746780170740405,89.54076865,196.4051593,-515.0733216,16.38127631
1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028192176989979435275,81.50964574,54.9572186,-150.3464233,10.36232088
1.3.6.1.4.1.14519.5.2.1.6279.6001.10268196240

In [ ]:
!grep 100225287222365663678666836860 data/part2/luna/annotations.csv

1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,-128.6994211,-175.3192718,-298.3875064,5.651470635
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,103.7836509,-211.9251487,-227.12125,4.224708481


In [27]:
!grep '100225287222365663678666836860.*,1$' data/part2/luna/candidates.csv

1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,104.16480444,-211.685591018,-227.011363746,1
1.3.6.1.4.1.14519.5.2.1.6279.6001.100225287222365663678666836860,-128.94,-175.04,-297.87,1


In [28]:
from p2ch12.vis import findPositiveSamples
positiveSample_list = findPositiveSamples()

2024-11-10 17:01:15,256 INFO     pid:15916 p2ch12.dsets:173:__init__ <p2ch12.dsets.LunaDataset object at 0x000001E47F9407C0>: 551065 training samples


0 CandidateInfoTuple(isNodule_bool=True, diameter_mm=32.27003025, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886', center_xyz=(67.61451718, 85.02525992, -109.8084416))
1 CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(47.90350511, 37.60442008, -99.93417567))
2 CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(44.19, 37.79, -107.01))
3 CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(40.69, 32.19, -97.15))
4 CandidateInfoTuple(isNodule_bool=True, diameter_mm=27.44242293, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.943403138251347598519939390311', center_xyz=(-45.29440163, 74.86925386, -97.52812481))
5 CandidateInfoTuple(isNodule_bool=True, dia

In [31]:
from p2ch12.dsets import getCt
positive_sample_example = positiveSample_list[0]
ct = getCt(positive_sample_example.series_uid)
ct

In [52]:
from p2ch12.dsets import LunaDataset
luna_dataset = LunaDataset()
for index in range(0, 30):
    sample = luna_dataset[index]
    print(f"Sample {index}, Tensor shape: {sample[0].shape}")
    print(sample[1])
    # print(sample[2])
    # print(sample[3])
    

2024-11-10 17:19:22,261 INFO     pid:15916 p2ch12.dsets:173:__init__ <p2ch12.dsets.LunaDataset object at 0x000001E422BC2B90>: 551065 training samples


Sample 0, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 1, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 2, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 3, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 4, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 5, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 6, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 7, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 8, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 9, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 10, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 11, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 12, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 13, Tensor shape: torch.Size([1, 32, 48, 48])
tensor([0, 1])
Sample 14, Tensor shape: torch.Size([1, 32, 48, 48])
tenso